version: '3.8'

services:
  db:
    image: postgres:16
    container_name: postgres-db
    restart: unless-stopped
    environment:
      POSTGRES_DB: default
      POSTGRES_USER: pc
      POSTGRES_PASSWORD: pc
    ports:
      - '127.0.0.1:5432:5432'
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U pc -d default']
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - pss-fs-network

  pss-fs:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pss-fs-app
    restart: unless-stopped
    ports:
      - '3000:3000'
    environment:
      # Database Configuration
      DB_HOST: db
      DB_USER: pc
      DB_PASSWORD: pc
      DB_NAME: default
      DB_PORT: 5432
      DB_SSLMODE: disable
      DB_TIMEZONE: UTC

      # Server Configuration
      PORT: 3000

      # File Storage Configuration
      FILES_DIRECTORY: /app/files
      MAX_FILE_SIZE: 0 # Unlimited file size
    volumes:
      - pss_fs_files:/app/files
    depends_on:
      db:
        condition: service_healthy
    networks:
      - pss-fs-network
    healthcheck:
      test: ['CMD', 'wget', '--no-verbose', '--tries=1', '--spider', 'http://localhost:3000/']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

volumes:
  postgres_data:
  pss_fs_files:
    driver: local

networks:
  pss-fs-network:
    driver: bridge
